name: Confirm pushed changes

on:
    push

jobs:
    ConfirmMssg:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Changes have been confirmed"
    Compile-program:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: javac *.java