name: Confirm pushed changes

on:
    push

jobs:
    ConfirmMssg:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Changes have been confirmed"
    Compile-program:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: javac *.java

    Build-project:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up JDK
              uses: actions/setup-java@v3
              with:
                java-version: '17'
                distribution: 'temurin'
                cache: maven
            - name: Build with maven
              run: mvn -B package --file pom.xml